### ISSUE TITLE
Disabling right-click on images

### ISSUE THREAD

**Issue by ebeshero** [arrowarchive/Old-Arrowarchive#2]
Hi @arrowarchive ! Here's a helpful resource we can start with for disabling right-click on your images:
http://www.pagetutor.com/no_right_click/

This code seems pretty straightforward, so I think it'll be easy to implement. Let's see if it works!

**Comment by arrowarchive** [comment]
@ebeshero I'll test it out and let you know how it goes. Thank you so much!!!

**Comment by arrowarchive** [comment]
@ebeshero, The code works for my profile picture, but not for the other picture on my page. I assume it is because my profile picture is in html and my other pictures are in markdown. 

Let me know when you can discuss this further.

**Comment by ebeshero** [comment]
@arrowarchive I think we'll need to convert your image code into html `<img>` elements for this to work.

**Comment by arrowarchive** [comment]
@ebeshero How would I do that? would I need to install a converter, or does _GitHub_ have something built in?

**Edit** Never mind, I figured out how to use it! I have a few more questions, but those involve researching disable drag-and-drop and removing access to my profile picture and repo files below my profile.

**Comment by arrowarchive** [comment]
@ebeshiro, Unfortunately, I have a new problem. Due to the way I have my thumbnails and images set up, I'm struggling to include the code in my website. It shows up as plain text instead of acting as a command. I can send a screenshot if necessary.

**Comment by arrowarchive** [comment]
@ebeshero, since disabling right-click has been managed (mostly. I may need help figuring out how to apply the command to my thumbnails), I have some other areas I want to work on next: 

1. First off, disable drag-and-drop. This is a common way for art to be stolen, and I sound paranoid, but I want my art to be as secure as possible. If we can figure out how to get this working, then the only way my work can be stolen is if someone takes a screenshot, or...

2. **...Accesses the original file through my repo**. The files can be accessed through my sidebar, and I want to make it so that neither my files or my profile can be accessed. It's an additional safety measure I want to take, to ensure that my work isn't stolen.

3. Lastly, I want to see if I can organize my repo after the latest assignments are graded. I intend to make a school folder within docs and store my assignments there, but I've been having trouble with it. This should be an easy fix, but I haven't had to make directories over _Git Bash_ in a while, so I may need a refresher. 

I'm excited to keep working on _Github_, and I appreciate your help as I learn the program!

**Comment by arrowarchive** [comment]
I should have specified what I said in class. I restored the thumbnails, which link to the full images, but I am wondering if it is possible to disable right click for the thumbnails. 

I typed a sequence of code to disable right click for a thumbnail, but the command only shows up as text. Here's a line of code and a screenshot of the result:

`[<img src="images/omabruh.png" alt="omabruh" height="130" width="130"/>](details/omabruh.md)`
`onContextMenu="return false;"> `

![Screenshot (105)](https://user-images.githubusercontent.com/70866633/96050591-e2794f80-0e47-11eb-8452-91d72b3baf66.png)

I understand if it isn't possible to disable right click here. There is a lot of data in the first line of code, and I've played with the brackets, but they interfere with the image preview.

**Comment by ebeshero** [comment]
@arrowarchive The code is showing because you haven't properly placed it inside the `<img>` tag. You have TWO tag endings, one inside and one outside your markdown link.  Revise thus:

```
[<img src="images/omabruh.png" alt="omabruh" height="130" width="130" onContextMenu="return false;"/>](details/omabruh.md)
```

Further: You won't be able to disable people visiting the code view of your repo, and nor can you ever prevent people from simply taking a screen capture of your page. I think you need to just live with the idea of websites being in public view. Just as you visit the web to find content to remix, you are also contributing to the web's available content. So what you share is only a sample to leave a professional calling card. 

Read about Creative Commons Licensing and choose a license to display on your site that makes sense to you: https://creativecommons.org/share-your-work/ 
That will help make your own intentions clear to others.

**Comment by arrowarchive** [comment]
The code worked! I'll have to do some research on creative commons licensing, since I have requested commissions of my own characters before (my profile picture is an example of this), and I have another that I am waiting for.

The commissions will not be used commercially. If I create a show using those characters in the future, the commissions will not be included in my portfolio.
